### ISSUE TITLE
`/query` endpoint roadmap

### ISSUE THREAD

**Issue by adrianmroz-allegro** [allegro/turnilo#1020]
### Required
- [ ] Ajax new static method
    - Should have partially applied AppSettings
    - Should be distributed in context
    - Remove Ajax.version and Ajax.settingsVersion
- [ ] `/query` endpoint
    - Introduce some dispatch for different query generation methods and/or different request schemas
    - Extract some validation logic that could be shared between `/query`, `/mkurl` and `plywood`
    - Move to common deserialization methods (`/query` and `/mkurl` need right now to convert app settings/data cube to client versions)

### Nice to have
- [ ] Remove plywood fields from ClientDataCube (and ClientMeasure ...), if needed introduce simple fields like `isApproximate` instead of inspecting expressions
- [ ] Create ClientEssence and ServerEssence
    - ClientEssence has additional UI fields like pinned measures, measure formats
    - ServerEssence can be simple POJsO with few convenience accessors - it is an ephemeral object, that's created for each request and destroyed after
- [ ] Introduce some mechanism for easy access to three objects - view definition, essence and hash on client. They are just three different views on the same data
- [ ] Rewrite fetching logic in components using hooks
    - Hook for comparing previous essence 
    - Hook for debounced fetch
    - Handle aborted DatasetRequests - right now we have some wierd null
- [ ] Remove Ajax.query and whole static class - functions are better
